---
eda_instance:
  name: eda
  instance_type: m4.xlarge
  disk_volume_type: gp3
  disk_space: 40
  disk_iops: 3000
  disk_throughput: 125
  host_aliases:
    - edacontroller
  ansible_extra_groups:
    - eda
