---
- name: "Configure AAP"
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  vars_files:
    - "~/agof_vault.yml"
  tasks:
    - name: "Configure AAP"
      ansible.builtin.include_role:
        name: hosts/roles/configure_aap
