# vim: ft=yaml.ansible
---
- name: "Configure AAP"
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  vars_files:
    - "~/agof_vault.yml"
  vars:
    ansible_async_dir: /tmp/.ansible_async
  tasks:
    - name: "Configure AAP"
      ansible.builtin.include_role:
        name: agof_configure_aap/roles/configure_aap
