---
- name: "Configure AAP"
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  collections:
    - redhat_cop.controller_configuration
  vars_files:
    - "vars/main.yml"
    - "~/agof_vault.yml"
  tasks:
    - name: Debug
      ansible.builtin.debug:
        var: controller_hostname

    - name: Include vars from configs directory
      ansible.builtin.include_vars:
        dir: "{{ controller_configs_dir }}"
        ignore_files: [controller_config.yml.template]
        extensions: ["yml"]
      tags:
        - always

    - name: "Configure AAP"
      ansible.builtin.include_role:
        name: dispatch
      when: not teardown|bool
