---
- name: "Pre-install: validate values and variables"
  hosts: localhost
  become: false
  gather_facts: false
  connection: local
  vars_files:
    - 'vars/main.yml'
    - '~/agof_vault.yml'
  vars:
    init_env_collection_install_force: true
  tasks:
    - name: "Show vars"
      ansible.builtin.debug:
        msg:
          - "automation_hub: {{ automation_hub }}"
          - "eda: {{ eda }}"

- name: "Phase 1 - initialize the environment"
  ansible.builtin.import_playbook: ./init_env/main.yml
  tags:
    - tags_phase_1

- name: "Phase 2 - containerized AAP install including bootstrap and configuration"
  ansible.builtin.import_playbook: ./containerized_install/main.yml
  tags:
    - tags_phase_2

- name: "Phase 3 - configure AAP (traditional install OR AGOF custom IAC install)"
  ansible.builtin.import_playbook: ./configure_aap.yml
  tags:
    - tags_phase_3
  when:
    - controller_postinstall_dir is not defined
    - controller_postinstall_repo_url is not defined
