---
- name: Debug
  ansible.builtin.debug:
    var: controller_hostname

- name: "Checkout infrastructure-as-code directory"
  ansible.builtin.git:
    repo: "{{ agof_iac_repo }}"
    version: "{{ agof_iac_repo_version | default('main') }}"
    dest: "{{ controller_configs_dir }}"
    force: true
    clone: true
    update: true
    recursive: true

- name: Include vars from configs directory
  ansible.builtin.include_vars:
    dir: "{{ controller_configs_dir }}"
    ignore_unknown_extensions: true
    extensions:
      - "json"
      - "yaml"
      - "yml"
  tags:
    - always

- name: Wait for Automation Controller to be up
  ansible.builtin.uri:
    url: 'https://{{ controller_hostname }}:{{ controller_port }}/api/v2/ping/'
    method: GET
    user: '{{ admin_user | default("admin") }}'
    password: "{{ admin_password }}"
    validate_certs: false
  register: check2
  until: check2.json is defined and check2.json.instances[0].capacity > 0 and check2.json.instance_groups[0].capacity > 0
  retries: 60
  delay: 10

- name: Display /api/v2/ping results
  ansible.builtin.debug:
    msg: '{{ check2.json }}'

- name: Post manifest file
  ansible.builtin.uri:
    url: 'https://{{ controller_hostname }}:{{ controller_port }}/api/v2/config/'
    method: POST
    user: '{{ admin_user | default("admin") }}'
    password: "{{ admin_password }}"
    body: '{ "eula_accepted": true, "manifest": "{{ manifest_content }}" }'
    body_format: json
    validate_certs: false
    force_basic_auth: true
  register: license_controller
  until: license_controller is not failed
  retries: 5

- name: "Configure AAP"
  ansible.builtin.include_role:
    name: infra.controller_configuration.dispatch
