---
- name: "Prepare AAP Installation"
  hosts: aap_controllers:automation_hub
  gather_facts: true
  become: true
  vars_files:
    - '~/agof_vault.yml'
  tasks:
    - name: "Download AAP"
      ansible.builtin.include_role:
        name: roles/aap_download

- name: "Configure controller"
  hosts: aap_controllers
  gather_facts: true
  become: true
  vars_files:
    - '~/agof_vault.yml'
  tasks:
    - name: "Install AAP"
      ansible.builtin.include_role:
        name: roles/control_node
      vars:
        controllerinstall: true

- name: "Configure Automation Hub"
  hosts: automation_hub
  gather_facts: true
  become: true
  vars_files:
    - '~/agof_vault.yml'
  tasks:
    - name: "Configure Automation Hub"
      ansible.builtin.include_role:
        name: roles/private_automation_hub
      when:
        - automation_hub|bool
