---
- name: Create directory for automation controller
  file:
    path: "{{ aap_dir }}"
    state: directory

- name: Install vimrc in home directory
  template:
    src: vimrc.j2
    dest: "/home/{{ username }}/.vimrc"
    owner: "{{ username }}"
    group: "{{ username }}"
