---
- name: Create directory for automation controller
  file:
    path: "{{ aap_dir }}"
    state: directory

- name: Extract AAP tar.gz install
  unarchive:
    src: "/root/aap.tar.gz"
    dest: "{{ aap_dir }}"
    remote_src: true
    extra_opts: ['--strip-components=1', '--show-stored-names']

- name: Set AAP local repository on controller node
  yum_repository:
    name: aap_installer
    description: aap_installer
    baseurl: "file:///{{ aap_dir }}/bundle/packages/el8/repos/"
    gpgcheck: false
  become: true

- name: Install vimrc in home directory
  template:
    src: vimrc.j2
    dest: "/home/{{ username }}/.vimrc"
    owner: "{{ username }}"
    group: "{{ username }}"
