---
# AWS specific initialization starts here
- name: "AWS specific network infrastructure reconfiguration to use IDM as DNS server"
  hosts: build_control
  remote_user: localhost
  connection: local
  become: false
  vars_files:
    - '~/agof_vault.yml'
  tasks:
    - name: "AWS inventory and DHCP option setting"
      block:
        - name: Include check code to setup variables
          ansible.builtin.include_role:
            name: roles/aws_check_setup
          when: ec2_vpc_id is not defined

        - name: Include setup code to populate VPC and other vars if not defined
          ansible.builtin.include_role:
            name: roles/manage_ec2_infra
          when: ec2_vpc_id is not defined

        - name: Get instances and inventory
          ansible.builtin.include_role:
            name: roles/manage_ec2_instances
          when: ec2_instances_built is not defined

        - name: "AWS-specific configuration to configure IDM as DNS Server for VPC"
          amazon.aws.ec2_vpc_dhcp_option:
            vpc_id: '{{ ec2_vpc_id }}'
            region: '{{ ec2_region }}'
            inherit_existing: true
            domain_name: '{{ pattern_domain }}'
            dns_servers:
              - "{{ idm_instance['private_ip_address'] }}"
          when: idm_instance is defined

- name: Restart NetworkManager to get nodes to pick up new DHCP options
  hosts: aws_nodes
  become: true
  gather_facts: true
  vars_files:
    - '~/agof_vault.yml'
  tasks:
    - name: "Restart NetworkManager on EC2 nodes"
      ansible.builtin.service:
        name: NetworkManager
        state: restarted

- name: Generic setup for AAP and Hub - set up repos, time, and IPA register
  hosts: aap_controllers:automation_hub
  become: true
  gather_facts: true
  vars_files:
    - '~/agof_vault.yml'
  tasks:
    - name: "Setup nodes"
      ansible.builtin.include_role:
        name: roles/generic_vm_setup
      when: build_aap_from_image
