---
# AWS specific initialization starts here
- name: "AWS specific initialization"
  hosts: build_control
  connection: local
  become: false
  vars_files:
    - "~/agof_vault.yml"
  vars:
    ec2_wait: true
  tasks:
    - name: collection final check
      block:
        - name: run AWS check setup if using AWS
          ansible.builtin.include_role:
            name: roles/aws_check_setup

      rescue:
        - name: Error with setup
          fail:
            msg: The provisioner has failed during initial check_setup, please scroll up to see exact error.

    - name: Provision network stuff
      ansible.builtin.include_role:
        name: roles/manage_ec2_infra

    - name: Build VMs and manage DNS entries
      ansible.builtin.include_role:
        name: roles/manage_ec2_instances

#    - name: Wait for EC2 servers to be available
#      ansible.builtin.wait_for:
#        host: "{{ item }}"
#        port: 22
#      loop:
#        - "{{ aap_instance['public_ip_address'] }}"
#        - "{{ hub_instance['public_ip_address'] }}"

- name: Post-provisioning tasks
  hosts: aws_nodes
  become: true
  gather_facts: true
  vars_files:
    - "vars/aws_vars.yml"
    - "~/agof_vault.yml"
  vars:
    ec2_instances_built: "{{ hostvars['localhost']['ec2_instances_built'] }}"
    ipaclient_configure_dns_resolver: false
  tasks:
#    - name: Set facts
#      ansible.builtin.set_fact:
#        idm_ip: "{{ idm_info.private_ip_address }}"
#        ipaserver_ip_addresses: "{{ idm_info.private_ip_address }}"
#        ipaclient_configure_dns_resolver: false

    - name: "Ensure remote tmp directory"
      ansible.builtin.file:
        path: '{{ aws_remote_tmp }}'
        mode: '0700'
        owner: '{{ ansible_user }}'
        recurse: true

    - name: 'Ensure hostname-setting can persist (thanks, cloud-init)'
      ansible.builtin.lineinfile:
        path: '/etc/cloud/cloud.cfg'
        regexp: '^\s*preserve_hostname:'
        line: 'preserve_hostname: true'

    - name: Set hostnames
      ansible.builtin.hostname:
        name: '{{ short_hostname }}.{{ pattern_domain }}'

    - name: Set /etc/hosts
      ansible.builtin.copy:
        content: |
          127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
          ::1         localhost localhost.localdomain localhost6 localhost6.localdomain6

          {% for ib in ec2_instances_built %}
          {{ ib.private_ip_address }}        {{ ib.tags.avpname }}.{{ pattern_domain }} {{ ec2_instances[ib.tags.avpname]['host_aliases'] | default([]) |  join(' ') }}
          {% endfor %}
        dest: /etc/hosts
        owner: root
        group: root
        mode: '0644'
