---
# Note: we always build AAP. It is in the defaults

- name: Add hub instance if desired
  when: automation_hub|bool
  block:
    - name: Include hub parameters
      ansible.builtin.include_vars:
        file: hub.yml

    - name: Include hub parameters
      ansible.builtin.set_fact:
        ec2_instances: '{{ ec2_instances + [ hub_instance ] }}'

- name: Add idm instance if desired
  when: build_idm|bool
  block:
    - name: Include idm parameters
      ansible.builtin.include_vars:
        file: idm.yml

    - name: Include idm parameters
      ansible.builtin.set_fact:
        ec2_instances: '{{ ec2_instances + [ idm_instance ] }}'

- name: Add satellite instance if desired
  when: build_sat|bool
  block:
    - name: Include satellite parameters
      ansible.builtin.include_vars:
        file: satellite.yml

    - name: Include satellite parameters
      ansible.builtin.set_fact:
        ec2_instances: '{{ ec2_instances + [ satellite_instance ] }}'

- name: overwrite select ec2_instaces vars if ec2_instances_xtra vars are provided
  set_fact:
    ec2_instances: '{{ ec2_instances|combine(ec2_instances_xtra) }}'
  when: (ec2_instances_xtra is defined) and (ec2_instances_xtra is not none)

- name: Provision machines
  ansible.builtin.include_tasks: ensure_ec2_instance.yml
  loop: '{{ ec2_instances }}'
  loop_control:
    loop_var: inst
  when: not teardown|bool

- name: Gather Inventory of built machines
  ansible.builtin.include_tasks: ensure_ec2_inventory.yml
  loop: '{{ ec2_instances }}'
  loop_control:
    loop_var: inst

- name: Manage Route53 DNS entries
  ansible.builtin.include_tasks: ensure_route53.yml
  when: manage_public_dns
  loop: '{{ ec2_instances_built }}'
  loop_control:
    loop_var: ec2_inst
