---
# Note: we always build AAP. It is in the defaults
- name: overwrite select ec2_instaces vars if ec2_instances_xtra vars are provided
  set_fact:
    ec2_instances: '{{ ec2_instances|combine(ec2_instances_xtra) }}'
  when: (ec2_instances_xtra is defined) and (ec2_instances_xtra is not none)

- name: See what machines we are building
  ansible.builtin.debug:
    var: ec2_instances

- name: Provision machines
  ansible.builtin.include_tasks: ensure_ec2_instance.yml
  loop: '{{ ec2_instances }}'
  loop_control:
    loop_var: inst
  when: not teardown|bool

- name: Gather Inventory of built machines
  ansible.builtin.include_tasks: ensure_ec2_inventory.yml
  loop: '{{ ec2_instances }}'
  loop_control:
    loop_var: inst

- name: Manage Route53 DNS entries
  ansible.builtin.include_tasks: ensure_route53.yml
  when: manage_public_dns
  loop: '{{ ec2_instances_built }}'
  loop_control:
    loop_var: ec2_inst
