---
aap_version: "2.4"

automation_hub: true
eda: true

# This is due to a known issue with version 1.0.7
# of EDA in AAP 2.4.
ci_24_eda_workaround: true

controller_fqdn: "{{ ansible_facts.fqdn }}"
controller_admin_password: "{{ admin_password }}"

postgresql_admin_username: 'postgres'
postgresql_admin_password: "{{ db_password }}"

controller_postinstall: false
controller_postinstall_dir: ''
controller_postinstall_repo_url: ''
controller_postinstall_repo_ref: 'main'

ee_extra_images: []
de_extra_images: []

controller_license_file: "/var/lib/aap/manifest.zip"

hub_admin_password: "{{ admin_password }}"
hub_pg_password: "{{ db_password }}"
hub_workers: 2
registry_username: "{{ redhat_username }}"
registry_password: "{{ redhat_password }}"

hub_postinstall: false
hub_postinstall_dir: ''
hub_postinstall_repo_url: ''
hub_postinstall_repo_ref: 'main'

hub_collection_signing: false
hub_collection_signing_key: ''

hub_container_signing: false
hub_container_signing_key: ''

eda_admin_password: "{{ admin_password }}"
eda_pg_password: "{{ db_password }}"
eda_workers: 2
eda_activation_workers: 2

force_aap_reconfigure: false
# These would be the defaults but we don't defined pattern_name to use the real FQDN
#controller_hostname: "aap.{{ pattern_name }}.{{ pattern_dns_zone }}"
controller_port: 8443

# controller_license_src_file:
# admin_password:
# db_password:
# redhat_username
# redhat_password
# postgresql_admin_username
