---
# Add EE to controller
- name: "Ensure the credential for the private automation hub"
  ansible.controller.credential:
    controller_host: "{{ active_controller }}"
    controller_username: "{{ aap_admin_username }}"
    controller_password: "{{ aap_admin_password }}"
    validate_certs: "{{ aap_validate_controller_certs }}"
    name: "Private Automation Hub"
    credential_type: "Container Registry"
    user: "admin"
    inputs:
      username: "{{ admin_username }}"
      password: "{{ admin_password }}"
      host: '{{ ansible_fqdn }}'

- name: "Ensure the EEs are registered on the controller"
  ansible.controller.execution_environment:
    controller_host: "{{ active_controller }}"
    controller_username: "{{ aap_admin_username }}"
    controller_password: "{{ aap_admin_password }}"
    validate_certs: "{{ aap_validate_controller_certs }}"
    name: "{{ ee.name }}"
    image: "{{ ee.image }}"
    pull: "{{ ee.pull | default(omit) }}"
    organization: "{{ ee.organization | default(omit) }}"
    description: "{{ ee.description | default(omit) }}"
    credential: "Private Automation Hub"
