---
# Build and upload an ee

- name: "Clone the git repo for the ee"
  ansible.builtin.git:
    repo: "{{ ee.git_repo }}"
    dest: "{{ ee.git_dest }}/{{ ee.name }}"
    clone: "{{ ee.git_clone | default(omit) }}"
    force: "{{ ee.git_force | default(omit) }}"

- name: "Add ansible.cfg template"
  ansible.builtin.template:
    src: "../templates/builder_ansible.cfg.j2"
    dest: "{{ ee.git_dest }}/{{ ee.name }}/ansible.cfg"

- name: "Look for a CA certificate"
  ansible.builtin.stat:
    path: /etc/ipa/ca.crt
  register: ca_stat

- name: "Add our ca certficate to the image"
  ansible.builtin.copy:
    src: "/etc/ipa/ca.crt"
    dest: "{{ ee.git_dest }}/{{ ee.name }}/context"
    remote_src: true
  when: ca_stat.stat.exists

- name: "Check on {{ ee.name }} local image"
  containers.podman.podman_image_info:
    name: '{{ ee.name }}'
  register: ee_rc
  failed_when: false

- name: "Build ee {{ ee.name }} on the target os"
  ansible.builtin.command: "ansible-builder build -t {{ ee.name }} --prune-images"
  args:
    chdir: "{{ ee.git_dest }}/{{ ee.name }}"
  async: 7200
  poll: 15
  when: ee_rc is not succeeded

- name: "Push the finished container for {{ ee.name }} to the hub"
  containers.podman.podman_image:
    name: "{{ ee.name }}"
    push: yes
    username: "{{ private_hub_username }}"
    password: "{{ private_hub_password }}"
    tlsverify: false
    push_args:
      dest: "{{ ansible_fqdn }}"
      remove_signatures: true
