- name: Configure Hub node
  include_tasks: "1_configurehub.yml"
  when: not teardown|bool

- name: install podman
  dnf:
    name: podman
    state: present
    disable_gpg_check: true
  when: automation_hub | bool and not teardown|bool
